config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin/index'
  get 'employee/index'

  
  get  'departament/index'
  get  'departament/new'
  post 'departament/create'=> 'departament#create', as: 'create_departament'
  put 'departament/:id' => 'departament#update', as: 'update_departament'
  delete 'departament/:id' => 'departament#destroy', as: 'delete_departament'

  resources :departament

  get  'employee/index' => 'employee#index', as: 'employee'
  get  'employee/new'
  get  'employee/:id/edit' => 'employee#edit', as: 'edit_employee'
  post 'employee/create'=> 'employee#create', as: 'create_employee'
  put 'employee/:id' => 'employee#update', as: 'update_employee'
  delete 'employee/:id' => 'employee#destroy', as: 'delete_employee'

  resources :employee

  get  'dayoff/index' => 'dayoff#index', as: 'dayoff'
  get  'dayoff/new'
  get  'dayoff/:id/edit' => 'dayoff#edit', as: 'edit_dayoff'
  post 'dayoff/create'=> 'dayoff#create', as: 'create_dayoff'
  put  'dayoff/:id' => 'dayoff#update', as: 'update_dayoff'
  delete 'dayoff/:id' => 'dayoff#destroy', as: 'delete_dayoff'

  resources :dayoff

  get  'vacation/index' => 'vacation#index', as: 'vacation'
  get  'vacation/new'
  get  'vacation/:id/edit' => 'vacation#edit', as: 'edit_vacation'
  post 'vacation/create'=> 'vacation#create', as: 'create_vacation'
  put  'vacation/:id' => 'vacation#update', as: 'update_vacation'
  delete 'vacation/:startid/:endid' => 'vacation#destroy', as: 'delete_vacation'

  resources :vacation
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :departament_id, presence: true
  validates :name, presence: true

  belongs_to :departament
  
  has_many :employees_days
  has_many :days, through: :employees_days
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_page, only: [:edit, :update, :destroy]
  
  
  @@employee_pagination = 30
  
  def index
  	@employees = Employee.paginate(page: params[:page], per_page: @@employee_pagination)
  end

  def new
  	@employee = Employee.new
  end

  def create
  	@employee = Employee.new(page_params)

  	if @employee.save
  		redirect_to employee_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @employee.update(page_params)
  		redirect_to employee_path
  	else
  		render :edit
  	end
  end
  

  def destroy
  	if @employee.destroy
  		redirect_to employee_path
  	else
  		redirect_to employee_path, error: 'Не удалось удалить отдел'
  	end
  end

  private
	  def page_params
	  	params[:employee].permit(:name, :departament_id)
	  end

  def find_page
  	@employee = Employee.find(params[:id])
  end
    
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employee/edit.html.erb
<h1>Редактировать работника</h1>

<%= simple_form_for @employee, url: update_employee_path(@employee)  do |f| %>
	<%= f.error_notification %>
	
	<%= f.input :name %>
	<%= f.association :departament %>
	<%= f.button :submit %>
<% end %>

app/views/employee/index.html.erb
<h4 class="text-center">Список работников</h4>
<div>
	<%= link_to 'Создать работника',  employee_new_path %>
</div>

<%= will_paginate @employees %>
<table class="table">
	<tbody>
		<tr>
			<th>
				имя
			</th>
			<th colspan="3">
				отдел
			</th>
		</tr>
	<% @employees.each do |employee| %>
		<tr>
			<td>
				<%= employee.name %>
			</td>
			<td>
				<%= employee.departament.name %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Edit',  edit_employee_path(employee) %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Delete', delete_employee_path(employee), :method=>:delete %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= will_paginate @employees %>

app/views/employee/new.html.erb
<h1>Создать работника</h1>

<%= simple_form_for @employee, url: create_employee_path do |f| %>
	<%= f.error_notification %>

	<%= f.input :name %>
	<%= f.association :departament %>
	<%= f.button :submit %>
<% end %>