config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin/index'
  get 'employee/index'

  
  get  'departament/index'
  get  'departament/new'
  post 'departament/create'=> 'departament#create', as: 'create_departament'
  put 'departament/:id' => 'departament#update', as: 'update_departament'
  delete 'departament/:id' => 'departament#destroy', as: 'delete_departament'

  resources :departament

  get  'employee/index' => 'employee#index', as: 'employee'
  get  'employee/new'
  get  'employee/:id/edit' => 'employee#edit', as: 'edit_employee'
  post 'employee/create'=> 'employee#create', as: 'create_employee'
  put 'employee/:id' => 'employee#update', as: 'update_employee'
  delete 'employee/:id' => 'employee#destroy', as: 'delete_employee'

  resources :employee

  get  'dayoff/index' => 'dayoff#index', as: 'dayoff'
  get  'dayoff/new'
  get  'dayoff/:id/edit' => 'dayoff#edit', as: 'edit_dayoff'
  post 'dayoff/create'=> 'dayoff#create', as: 'create_dayoff'
  put  'dayoff/:id' => 'dayoff#update', as: 'update_dayoff'
  delete 'dayoff/:id' => 'dayoff#destroy', as: 'delete_dayoff'

  resources :dayoff

  get  'vacation/index' => 'vacation#index', as: 'vacation'
  get  'vacation/new'
  get  'vacation/:id/edit' => 'vacation#edit', as: 'edit_vacation'
  post 'vacation/create'=> 'vacation#create', as: 'create_vacation'
  put  'vacation/:id' => 'vacation#update', as: 'update_vacation'
  delete 'vacation/:startid/:endid' => 'vacation#destroy', as: 'delete_vacation'

  resources :vacation
  

end

app/controllers/dayoff_controller.rb
class DayoffController < ApplicationController
   
   before_filter :find_page, only: [:edit, :update, :destroy]

   @@dayoffs_type = 1
   @@dayoffs_pagination = 100
   

 def index
 @dayoffs = EmployeesDay.paginate(page: params[:page], per_page: @@dayoffs_pagination).
				joins('INNER JOIN days ON days.id = employees_days.day_id')
				.where('kind = ? AND days.date >= ?', @@dayoffs_type, Date.current)
				.order('employee_id DESC, day_id ASC')
 end
 
 def destroy
  	if @dayoff.destroy
  		redirect_to dayoff_path
  	else
  		redirect_to dayoff_path, error: 'Не удалось удалить выходной или отгул'
  	end
 end

 def new
  	@dayoff = EmployeesDay.new
 end

 def create
  	@dayoff = EmployeesDay.new
  	@day = Day.find_by date: Date.parse(page_params[:day_start]);
  	@dayId = @day.id
  	@employeeId = page_params[:employee_id]
  	
  	@isExistEmployeesDay = EmployeesDay
		.where('employee_id = ? AND day_id = ?', @employeeId, @dayId)
	if @isExistEmployeesDay
		@isExistEmployeesDay.destroy_all
	end
		
  	@dayoff.day_id = @dayId;
	@dayoff.employee_id = @employeeId
  	@dayoff.kind = @@dayoffs_type
  
  	if @dayoff.save
  		redirect_to dayoff_path
  	else
  		render :new
  	end
 end

 def edit
 end

 def update
  	@dayId = page_params[:day_id]
  	@employeeId = page_params[:employee_id]

  	@isExistEmployeesDay = EmployeesDay
		.where('employee_id = ? AND day_id = ?', @employeeId, @dayId)
	if @isExistEmployeesDay
		@isExistEmployeesDay.destroy_all
	end

  	if @dayoff.update(page_params)
  		redirect_to dayoff_path
  	else
  		render :edit
  	end
 end


 private
	  def page_params
	  	params[:employees_day].permit(:employee_id, :day_id, :day_start, :day_end)
	  end

 def find_page
  	@dayoff = EmployeesDay.find_by_id(params[:id])  	
 end

end

app/helpers/dayoff_helper.rb
module DayoffHelper
end

app/views/dayoff/edit.html.erb
<h4>Редактировать выходной или отгул</h4>

<%= simple_form_for @dayoff, url: update_dayoff_path do |f| %>
	<%= f.error_notification %>
	
	<%= f.association :employee %>
	<%= f.association :day, :label_method => :date, :value_method => :id %>
	
	<%= f.button :submit %>
<% end %>

app/views/dayoff/index.html.erb
<h4 class="text-center">Список выходных и отгулов</h4>

<div>
	<%= link_to 'Добавить выходной или отгул',  dayoff_new_path %>
</div>
<%= will_paginate @dayoffs %>
<table class="table">
	<tbody>
		<tr>
			<th>
				имя
			</th>
			<th>
				отдел
			</th>
			<th colspan="3">
				дата
			</th>
		</tr>
	<% @dayoffs.each do |dayoff| %>
		<tr>
			<td>
				<%= dayoff.employee.name %>
			</td>
			<td>
				<%= dayoff.employee.departament.name %>
			</td>
			<td>
				<%= dayoff.day.date.strftime("%m/%d/%Y") %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Изменить',  edit_dayoff_path(dayoff) %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Удалить', delete_dayoff_path(dayoff), :method=>:delete %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= will_paginate @dayoffs %>

app/views/dayoff/new.html.erb
<h4>Добавить выходной или отгул</h4>

<%= simple_form_for @dayoff, url: create_dayoff_path do |f| %>
	<%= f.error_notification %>

	<%= f.association :employee %>
		
	<%= date_field(:employees_day, :day_start) %>
	<%= f.button :submit %>
<% end %>