config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin/index'
  get 'employee/index'

  
  get  'departament/index'
  get  'departament/new'
  post 'departament/create'=> 'departament#create', as: 'create_departament'
  put 'departament/:id' => 'departament#update', as: 'update_departament'
  delete 'departament/:id' => 'departament#destroy', as: 'delete_departament'

  resources :departament

  get  'employee/index' => 'employee#index', as: 'employee'
  get  'employee/new'
  get  'employee/:id/edit' => 'employee#edit', as: 'edit_employee'
  post 'employee/create'=> 'employee#create', as: 'create_employee'
  put 'employee/:id' => 'employee#update', as: 'update_employee'
  delete 'employee/:id' => 'employee#destroy', as: 'delete_employee'

  resources :employee

  get  'dayoff/index' => 'dayoff#index', as: 'dayoff'
  get  'dayoff/new'
  get  'dayoff/:id/edit' => 'dayoff#edit', as: 'edit_dayoff'
  post 'dayoff/create'=> 'dayoff#create', as: 'create_dayoff'
  put  'dayoff/:id' => 'dayoff#update', as: 'update_dayoff'
  delete 'dayoff/:id' => 'dayoff#destroy', as: 'delete_dayoff'

  resources :dayoff

  get  'vacation/index' => 'vacation#index', as: 'vacation'
  get  'vacation/new'
  get  'vacation/:id/edit' => 'vacation#edit', as: 'edit_vacation'
  post 'vacation/create'=> 'vacation#create', as: 'create_vacation'
  put  'vacation/:id' => 'vacation#update', as: 'update_vacation'
  delete 'vacation/:startid/:endid' => 'vacation#destroy', as: 'delete_vacation'

  resources :vacation
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workindays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<div>
	<% if user_signed_in? %>
	    <span>Здравствуйте, <%= current_user.email %></span>
	    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
	<% else %>
	    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
	<% end %>
	</div>

	<% if user_signed_in? %>
	<div>
    <br />
    <ul class="nav nav-justified">
      <li class="active">
      	<%= link_to 'Управление отделами',  departament_index_path %>
      </li>
      <li class="active">
      	<%= link_to 'Админ панель',  admin_index_path %>
      </li>
      <li>
      	<%= link_to 'Управление работниками', employee_index_path %>
      </li>
    </ul>
  </div>
  <% end %>
  
  <br />
  <div>
    <%= link_to 'Управление выходными', dayoff_path, :class=>"btn btn-primary btn-sm btn-block" %>
      
    <%= link_to 'Главная',  '/', :class => "btn btn-primary btn-sm btn-block" %>
      
    <%= link_to 'Управление отпусками', vacation_path, :class =>"btn btn-primary btn-sm btn-block" %>
  </div>
  <br />

	<%= yield %>
</div>
</body>
</html>