config/routes.rb
Rails.application.routes.draw do
   
  devise_for :users

  get 'admin/index', as: 'user_root'

  get 'admin/index'
  get 'employee/index'

  
  get  'departament/index'
  get  'departament/new'
  post 'departament/create'=> 'departament#create', as: 'create_departament'
  put 'departament/:id' => 'departament#update', as: 'update_departament'
  delete 'departament/:id' => 'departament#destroy', as: 'delete_departament'

  resources :departament

  get  'employee/index' => 'employee#index', as: 'employee'
  get  'employee/new'
  get  'employee/:id/edit' => 'employee#edit', as: 'edit_employee'
  post 'employee/create'=> 'employee#create', as: 'create_employee'
  put 'employee/:id' => 'employee#update', as: 'update_employee'
  delete 'employee/:id' => 'employee#destroy', as: 'delete_employee'

  resources :employee

  get  'dayoff/index' => 'dayoff#index', as: 'dayoff'
  get  'dayoff/new'
  get  'dayoff/:id/edit' => 'dayoff#edit', as: 'edit_dayoff'
  post 'dayoff/create'=> 'dayoff#create', as: 'create_dayoff'
  put  'dayoff/:id' => 'dayoff#update', as: 'update_dayoff'
  delete 'dayoff/:id' => 'dayoff#destroy', as: 'delete_dayoff'

  resources :dayoff

  get  'vacation/index' => 'vacation#index', as: 'vacation'
  get  'vacation/new'
  get  'vacation/:id/edit' => 'vacation#edit', as: 'edit_vacation'
  post 'vacation/create'=> 'vacation#create', as: 'create_vacation'
  put  'vacation/:id' => 'vacation#update', as: 'update_vacation'
  delete 'vacation/:startid/:endid' => 'vacation#destroy', as: 'delete_vacation'

  resources :vacation
  

end

app/models/departament.rb
class Departament < ActiveRecord::Base
	validates :name, presence: true
	
	has_many :employee
end

app/controllers/departament_controller.rb
class DepartamentController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_page, only: [:edit, :update, :show, :destroy]

  @@departaments_pagination = 10

  def index
  	@departaments = Departament.paginate(page: params[:page], per_page: @@departaments_pagination)
  end

  def new
  	@departament = Departament.new
  end

  def create
  	@departament = Departament.new(page_params)

  	if @departament.save
  		redirect_to departament_index_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @department.update(page_params)
  		redirect_to departament_index_path
  	else
  		render :edit
  	end
  end

  def destroy
  	if @department.destroy
  		redirect_to departament_index_path
  	else
  		redirect_to departament_index_path, error: 'Не удалось удалить отдел'
  	end
  end

  private
	  def page_params
	  	params[:departament].permit(:name)
	  end

  def find_page
  	@department = Departament.find(params[:id])
  end

end

app/helpers/departament_helper.rb
module DepartamentHelper
end

app/views/departament/edit.html.erb
<h1>Редактировать отдел</h1>

<%= simple_form_for @department, url: update_departament_path(@department)  do |f| %>
	<%= f.error_notification %>
	
	<%= f.input :name %>
	<%= f.button :submit %>
<% end %>

app/views/departament/index.html.erb
<h4 class="text-center">Список отделов</h4>
<div>
	<%= link_to 'Создать отдел',  departament_new_path %>
</div>

<%= will_paginate @departaments %>
<table class="table">
	<tbody>
		<tr>
			<th colspan="3">
				название
			</th>
		</tr>
	<% @departaments.each do |department| %>
		<tr>
			<td>
				<%= department.name %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Edit',  edit_departament_path(department) %>
			</td>
			<td class="indexTableTd text-right">
				<%= link_to 'Delete', delete_departament_path(department), :method=>:delete %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= will_paginate @departaments %>

app/views/departament/new.html.erb
<h1>Создать отдел</h1>

<%= simple_form_for @departament, url: create_departament_path do |f| %>
	<%= f.error_notification %>

	<%= f.input :name %>
	<%= f.button :submit %>
<% end %>